@server = http://localhost:3000

### 게시글 작성
POST  {{server}}/user/createUser
Content-Type: application/json

{
    "username":"realcom",
    "password":"112233",
    "email":"tjalswhd11345@gmail.com"
}

### 게시글 조회
GET {{server}}/user/getUser/tjalswhd11345@gmail.com


### 게시글 수정
PUT {{server}}/user/updateUser/tjalswhd11345@gmail.com
content-Type: application/json

{
    "username":"new realcom",
    "password":"332211",
    "email":"tjalswhd11345@naver.com"
}

### 게시글 삭제
DELETE {{server}}/user/deleteUser/tjalswhd11345@gmail.com

### 잘못된 생성 요청
POST  {{server}}/user/createUser
Content-Type: application/json

{
    "username":"realcom",
    "password":"112233",
    "email":"jkk0011"
}

### register check
POST {{server}}/auth/register
Content-Type: application/json

{
    "username":"bad realcom",
    "password":"111333",
    "email":"tjalswhd11345@gmail.com"
}

### login test
POST {{server}}/auth/login
Content-Type: application/json

{
    "email": "tjalswhd11345@gmail.com",
    "password": "111333"
}